/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:38.032861
 */
package bio.ferlab.etl.normalized.model

case class NORMALIZED_TASK(`fhir_id`: String = "SXP0000003",
                           `owner`: String = "CQDG",
                           `bio_informatic_analysis`: Option[String] = None,
                           `labAliquotID`: String = "1000004041-A10",
                           `ldm_sample_id`: String = "S03357",
                           `run_name`: String = "1612",
                           `read_length`: Option[String] = None,
                           `is_paired_end`: Boolean = true,
                           `run_alias`: Option[String] = None,
                           //                           `run_date`: String = "1969-12-31 19:19:36.5088",
                           `capture_kit`: Option[String] = None,
                           `platform`: String = "Illumina HiSeq 2000 PE100",
                           `experimental_strategy`: String = "WGS",
                           `sequencer_id`: Option[String] = None,
                           `workflow_name`: String = "Dragen",
                           `workflow_version`: String = "3.9.3",
                           `genome_build`: String = "GRCh38",
                           `_for`: String = "PRT0000002",
                           `alir`: String = "FIL0000007",
                           `snv`: String = "FIL0000016",
                           `gcnv`: String = "FIL0000008",
                           `gsv`: String = "FIL0000009",
                           `ssup`: String = "FIL0000010",
                           `study_id`: String = "STU0000001",
                           `release_id`: Int = 1)

