/** Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]] on 2025-06-17T11:55:10.623147
  */
package model.input

case class LIST_INPUT(
    `fhir_id`: String = "cqdg-program-rare-qc",
    `name_en`: String = "RARE.Qc",
    `name_fr`: String = "RARE.Qc – Le réseau pour avancer la recherche en maladies rares au Québec",
    `study_codes`: Seq[String] = Seq("STU0000001"),
    `program_id`: String = "RARE-QC",
    `description_fr`: String = "RARE.Qc est un réseau québécois",
    `description_en`: String = "RARE.Qc is a Quebec-based.",
    `research_program_related_artifact`: RESEARCH_PROGRAM_RELATED_ARTIFACT = RESEARCH_PROGRAM_RELATED_ARTIFACT(),
    `research_program_contacts`: Seq[RESEARCH_PROGRAM_CONTACTS] = Seq(
      RESEARCH_PROGRAM_CONTACTS(`telecom` = Seq.empty[TELECOM]),
      RESEARCH_PROGRAM_CONTACTS(
        `name` = null,
        `institution` = "RI-MUHC",
        `role_en` = null,
        `role_fr` = null,
        `picture_url` = null,
        `telecom` = Seq(TELECOM(), TELECOM(`value` = "info@rare.quebec", `system` = "email"))
      )
    ),
    `research_program_partners`: Seq[RESEARCH_PROGRAM_PARTNERS] = Seq(
      RESEARCH_PROGRAM_PARTNERS(),
      RESEARCH_PROGRAM_PARTNERS(`name` = "Genome Quebec", `logo` = "/partners_logos/genome_qc.svg", `rank` = 1)
    )
)

case class RESEARCH_PROGRAM_RELATED_ARTIFACT(
    `website`: String = "https://rare.quebec",
    `citation_statement`: String = "The results analyzed",
    `logo_url`: Option[String] = None
)

case class RESEARCH_PROGRAM_CONTACTS(
    `name`: String = "Toto Tata",
    `institution`: String = "CHU Sainte-Justine",
    `role_en`: String = "Manager",
    `role_fr`: String = "Gestionnaire",
    `picture_url`: String = "/members_pictures/toto_tata.png",
    `telecom`: Seq[TELECOM] = Seq(TELECOM())
)

case class TELECOM(`value`: String = "https://rare.quebec", `system`: String = "url")

case class RESEARCH_PROGRAM_PARTNERS(
    `name`: String = "FRQS",
    `logo`: String = "/partners_logos/FRQS.svg",
    `rank`: Int = 2
)
