/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:38.032861
 */
package models




case class NORMALIZED_TASK(`fhir_id`: String = "SXP0000001",
                           `owner`: String = "CQDG",
                           `bio_informatic_analysis`: Option[String] = None,
                           `labAliquotID`: String = null, //FIXME
                           `ldm_sample_id`: String = null,  //FIXME
                           `run_name`: String = null, //FIXME
                           `read_length`: Option[String] = Some("151"),
                           `is_paired_end`: Boolean = true,
                           `run_alias`: Option[String] = None,
                           `run_date`: String = null, //FIXME
                           `capture_kit`: Option[String] = None,
                           `platform`: String = "Illumina HiSeq 2000 PE100",
                           `experimental_strategy`: String = "WGS",
                           `sequencer_id`: Option[String] = None,
                           `workflow_name`: String = null,
                           `workflow_version`: String = null, //FIXME
                           `genome_build`: String = "GRCh38",
                           `_for`: String = "PRT0000003",
                           `analysis_files`: Seq[ANALYSIS_FILE] = Seq(
                             ANALYSIS_FILE("Annotated-SNV", "FIL0000101"),
                             ANALYSIS_FILE("Aligned-reads", "FIL0000102"),
                             ANALYSIS_FILE("SNV", "FIL0000104"),
                             ANALYSIS_FILE("Germline-CNV", "FIL0000106"),
                             ANALYSIS_FILE("Germline-structural-variant", "FIL0000108"),
                             ANALYSIS_FILE("Sequencing-data-supplement", "FIL0000110"),
                           ),
                           `study_id`: String = "study1")

case class ANALYSIS_FILE(
                          data_type: String,
                          file_id: String,
                        )
