/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:22.607392
 */
package models




case class NORMALIZED_SAMPLE_REGISTRATION(`subject`: String = "PRT0000001",
                                          `parent`: String = "BIO0000003",
                                          `fhir_id`: String = "SAM0000002",
                                          `sample_type`: SAMPLE_TYPE = SAMPLE_TYPE(),
                                          `submitter_sample_id`: String = "S03387",
                                          `study_id`: String = "study1")

case class SAMPLE_TYPE(`system`: String = "http://purl.obolibrary.org/obo/ncit.owl",
                       `code`: String = "NCIT:C449")
