/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:23.966397
 */
package models




case class NORMALIZED_RESEARCH_STUDY(`fhir_id`: String = "study1",
                                     `keyword`: Seq[String] = Seq("epilepsy", "developmental disorder", "family trios"),
                                     `description`: String = "Case-parent trio study on developmental and epileptic encephalopaties (DEE)",
                                     `access_authority`: ACCESS_AUTHORITY = ACCESS_AUTHORITY(),
                                     `contact_names`: Seq[String] = Seq("James Gordon 2", "Lois Lane 2"),
                                     `contact_institutions`: Seq[String] = Seq("Metropolis University", "Gotham University"),
                                     `contact_emails`: Seq[String] = Seq("jgordon2@gpd.com", "llane@mpd.com"),
                                     `principal_investigators`: Seq[String] = Seq("Batman2", "Superman2"),
                                     `citation_statement`: String = null,
                                     `selection_criteria`: String = "Children with a diagnosis of intractable seizures",
                                     `funding_sources`: Seq[String] = Seq("funding_source1", "funding_source2"),
                                     `status`: String = "completed",
                                     `title`: String = "Developmental and epileptic encephalopathies",
                                     `website`: String = "http://study2.com",
                                     `domain`: Seq[String] = Seq("neurodevelopmental-conditions"),
                                     `study_code`: String = "STUDY1",
                                     `access_limitations`: Seq[ACCESS_LIMITATIONS] = Seq(ACCESS_LIMITATIONS()),
                                     `access_requirements`: Seq[ACCESS_REQUIREMENTS] = Seq(ACCESS_REQUIREMENTS(), ACCESS_REQUIREMENTS(`code` = "DUO:0000021"), ACCESS_REQUIREMENTS(`code` = "DUO:0000026")),
                                     `population`: String = "Pediatric and Adult",
                                     `study_version`: String = "1",
                                     `expected_number_participants`: String = "5",
                                     `expected_number_biospecimens`: String = "5",
                                     `expected_number_files`: String = "32",
                                     `restricted_number_participants`: String = null,
                                     `restricted_number_biospecimens`: String = null,
                                     `restricted_number_files`: String = null,
                                     `data_categories`: Seq[String] = Seq("genomics"),
                                     `study_designs`: Seq[String] = Seq("case_only", "registry"),
                                     `data_collection_methods`: Seq[String] = Seq("investigator_assessment", "participant_caregiver_report"),
                                     `data_sets`: Seq[DATA_SETS] = Seq(DATA_SETS(), DATA_SETS(`name` = "d2", `description`= "description 2")),
                                     `study_id`: String = "study1",
                                     `security` : String = "U")

case class ACCESS_AUTHORITY(`type`: String = "email",
                   `value`: String = "jacques.michaud.med@ssss.gouv.qc.ca")

case class ACCESS_LIMITATIONS(`code`: String = "DUO:0000006",
                              `display`: Option[String] = None)

case class ACCESS_REQUIREMENTS(`code`: String = "DUO:0000016",
                               `display`: Option[String] = None)

case class DATA_SETS(`name`: String = "d1",
                     `description`: String = "description 1")
