/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:38.032861
 */
package models




case class NORMALIZED_TASK(`fhir_id`: String = "SXP0000001",
                           `owner`: String = "CQDG",
                           `bio_informatic_analysis`: Option[String] = None,
                           `lab_aliquot_ids`: Seq[String] = Seq("1000004041-A11"),
                           `ldm_sample_id`: String = "S16523",
                           `run_ids`: Seq[String] = Seq("2018"),
                           `run_dates`: Seq[String] = Seq("2007-04-14"),
                           `selection`: CODEABLE =  CODEABLE("RR"),
                           `source`: CODEABLE = CODEABLE("TSC"),
                           `protocol`: String = "protocol2",
                           `target_capture_kit`: String = "targetCaptureKit3",
                           `target_loci`: String = "targetedLoci2",
                           `pipeline`: String = "testPipeline",
                           `read_length`: Option[String] = Some("151"),
                           `is_paired_end`: Boolean = true,
                           `capture_kit`: Option[String] = None,
                           `platform`: String = "Illumina HiSeq 2000 PE100",
                           `experimental_strategy_1`: CODEABLE = CODEABLE("WGS"),
                           `experimental_strategy`: String = "WGS",
                           `sequencer_id`: Option[String] = None,
                           `genome_build`: String = "GRCh38",
                           `_for`: String = "PRT0000002",
                           `analysis_files`: Seq[ANALYSIS_FILE] = Seq(
                             ANALYSIS_FILE("Annotated-SNV", "FIL0000101"),
                             ANALYSIS_FILE("Aligned-reads", "FIL0000102"),
                             ANALYSIS_FILE("SNV", "FIL0000104"),
                             ANALYSIS_FILE("Germline-CNV", "FIL0000106"),
                             ANALYSIS_FILE("Germline-structural-variant", "FIL0000108"),
                             ANALYSIS_FILE("Metrics", "FIL0000605"),
                             ANALYSIS_FILE("Unaligned-Reads", "FIL0000515"),
                             ANALYSIS_FILE("Unaligned-Reads", "FIL0000516"),
                           ),
                           `study_id`: String = "study1")

case class ANALYSIS_FILE(
                          data_type: String,
                          file_id: String,
                        )
