/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:21.292480
 */
package models




case class NORMALIZED_BIOSPECIMEN(`fhir_id`: String = "BIO0000001",
                                  `subject`: String = "PRT0000001",
                                  `biospecimen_tissue_source`: BIOSPECIMEN_TISSUE_SOURCE = BIOSPECIMEN_TISSUE_SOURCE(),
                                  `age_biospecimen_collection`: AGE_BIOSPECIMEN_COLLECTION = AGE_BIOSPECIMEN_COLLECTION(),
                                  `submitter_biospecimen_id`: String = "biospecimen21162",
                                  `study_id`: String = "STU0000001",
                                  `release_id`: Int = 1)

case class BIOSPECIMEN_TISSUE_SOURCE(`system`: String = "http://purl.obolibrary.org/obo/ncit.owl",
                                     `code`: String = "NCIT:C12434",
                                     `display`: Option[String] = None)

case class AGE_BIOSPECIMEN_COLLECTION(`value`: Long = 20830,
                                      `unit`: String = "days")
