/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:17.500947
 */
package models




case class NORMALIZED_DIAGNOSIS(`subject`: String = "PRT0000001",
                                `fhir_id`: String = "DIA0000003",
                                `diagnosis_source_text`: String = "Eczema",
                                `diagnosis_mondo_code`: String = "MONDO:0004980",
                                `diagnosis_ICD_code`: String = "L20.9",
                                `age_at_diagnosis`: AGE_AT_DIAGNOSIS = AGE_AT_DIAGNOSIS(),
                                `study_id`: String = "STU0000001",
                                `release_id`: Int = 1)

case class AGE_AT_DIAGNOSIS(`value`: Int = 0,
                            `unit`: String = "days")
