/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:17.500947
 */
package models




case class NORMALIZED_DIAGNOSIS(`subject`: String = "PRT0000001",
                                `fhir_id`: String = "DIA0000002",
                                `diagnosis_source_text`: String = "Intractable Epilepsy",
                                `diagnosis_mondo_code`: String = "MONDO:0005027",
                                `diagnosis_ICD_code`: String = "G40.31",
                                `age_at_diagnosis`: String = "HP:0011462",
                                `study_id`: String = "study1")
