/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:36.153900
 */
package models




case class NORMALIZED_GROUP(`internal_family_id`: String = "12345STU0000001",
                            `family_type`: String = "Case-parent trio",
                            `family_members`: Seq[String] = Seq("PRT0000001", "PRT0000002", "PRT0000003"),
                            `submitter_family_id`: String = "12345",
                            `study_id`: String = "STU0000001",
                            `release_id`: Int = 1)

