/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:16.067901
 */
package models




case class NORMALIZED_PATIENT(`fhir_id`: String = "PRT0000001",
                              `sex`: String = "female",
                              `deceasedBoolean`: Boolean = false,
                              `age_at_recruitment`: String = "HP:0003584",
                              `ethnicity`: String = "French Canadian",
                              `submitter_participant_id`: String = "35849409716",
                              `vital_status`: String = "Alive",
                              `age_of_death`: String = "HP:0003593",
                              `study_id`: String = "CAG",
                              `security`: String = "R")

