/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:16.067901
 */
package models




case class NORMALIZED_PATIENT(`fhir_id`: String = "PRT0000001",
                              `gender`: String = "female",
                              `deceasedBoolean`: Boolean = false,
                              `age_at_recruitment`: Int = 21975,
                              `ethnicity`: String = "French Canadian",
                              `submitter_participant_id`: String = "35849409716",
                              `vital_status`: String = "Alive",
                              `age_of_death`: Int = 50,
                              `study_id`: String = "STU0000001",
                              `release_id`: Int = 1)

