/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:34.831337
 */
package models




case class NORMALIZED_FAMILY_RELATIONSHIP(`internal_family_relationship_id`: String = "FAM0000001FR",
                                          `category`: String = "SOCIALHISTORY",
                                          `submitter_participant_id`: String = "PRT0000001",
                                          `focus_participant_id`: String = "PRT0000003",
                                          `relationship_to_proband`: String = "Mother",
                                          `study_id`: String = "STU0000001",
                                          `release_id`: Int = 1)

