/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-17T11:40:58.129806
 */
package models




case class NORMALIZED_DOCUMENT_REFERENCE(`fhir_id`: String = "FIL0000207",
                                         `participant_id`: String = "PRT0000003",
                                         `biospecimen_reference`: String = "SAM0000003",
                                         `data_type`: String = "Sequencing-data-supplement",
                                         `data_category`: String = "genomics",
                                         `dataset`: String = "ds_name_1",
                                         `files`: Seq[FILES] = Seq(FILES()),
                                         `study_id`: String = "CAG",
                                         `relates_to`: Option[String] = None,
                                         `security`: String = "R")

case class FILES(`file_name`: String = "FIL0000207.mpsMetrics_S03344.tar.gz",
                 `file_format`: String = "TGZ",
                 `file_size`: Float = 8.0f,
                 `ferload_url`: String = "s3://cqdg-dev-file-import/run_432/CAG/dataset_ds_name_1/1623/mpsMetrics_S03344.tar.gz",
                 `file_hash`: Option[String] = None)
