/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:20.018137
 */
package models




case class NORMALIZED_PHENOTYPE(`fhir_id`: String = "PHE0000002",
                                `age_at_phenotype`: String = "HP:0003596",
                                `phenotype_source_text`: String = "Hypertension",
                                `phenotype_HPO_code`: PHENOTYPE_HPO_CODE = PHENOTYPE_HPO_CODE(),
                                `cqdg_participant_id`: String = "PRT0000002",
                                `phenotype_observed`: String = "POS",
                                `study_id`: String = "STU0000001",
                                `release_id`: String = "1")

case class PHENOTYPE_HPO_CODE(`system`: String = "http://purl.obolibrary.org/obo/hp.owl",
                              `code`: String = "HP:0000822")
