/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-08-11T19:42:18.950951
 */
package models




case class NORMALIZED_DISEASE_STATUS(`fhir_id`: String = "FAM0000001DS",
                                     `subject`: String = "PRT0000001",
                                     `disease_status`: String = "Unknown",
                                     `study_id`: String = "STU0000001",
                                     `release_id`: Int = 1)

