/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2023-06-07T14:55:23.017
 */
package bio.ferlab.etl.normalize.model

import java.sql.Timestamp


case class NormalizedConsequences(`chromosome`: String = "1",
                                  `start`: Long = 10230,
                                  `reference`: String = "AC",
                                  `alternate`: String = "A",
                                  `name`: Option[String] = None,
                                  `end`: Long = 10232,
                                  `consequences`: Seq[String] = Seq("upstream_gene_variant"),
                                  `impact`: String = "MODIFIER",
                                  `symbol`: String = "DDX11L2",
                                  `ensembl_gene_id`: String = "ENSG00000290825",
                                  `ensembl_feature_id`: String = "ENST00000456328",
                                  `ensembl_transcript_id`: String = "ENST00000456328",
                                  `ensembl_regulatory_id`: Option[String] = None,
                                  `feature_type`: String = "Transcript",
                                  `strand`: String = "1",
                                  `biotype`: String = "lncRNA",
                                  `variant_class`: String = "deletion",
                                  `exon`: Exon = Exon(),
                                  `intron`: Intron = Intron(),
                                  `hgvsc`: Option[String] = None,
                                  `hgvsp`: Option[String] = None,
                                  `hgvsg`: String = "chr1:g.10234del",
                                  `cds_position`: Option[String] = None,
                                  `cdna_position`: Option[String] = None,
                                  `protein_position`: Option[String] = None,
                                  `amino_acids`: AMINO_ACIDS = AMINO_ACIDS(),
                                  `codons`: CODONS = CODONS(),
                                  `original_canonical`: Boolean = true,
                                  `refseq_mrna_id`: Option[Seq[String]] = None,
                                  `aa_change`: Option[String] = None,
                                  `coding_dna_change`: Option[String] = None,
                                  `impact_score`: Int = 1)

