/** Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]] on 2023-05-31T14:04:51.825
  */
package model

case class SPECIMEN_ENRICHED(
    `study_id`: String = "STU0000001",
    `participant_id`: String = "P2",
    `biospecimen_id`: String = "FHIR_BS_2",
    `security`: String = "U",
    `submitter_participant_id`: String = "P2_internal",
    `biospecimen_tissue_source`: String = "Blood (NCIT:C12434)",
    `age_biospecimen_collection`: String = "Young",
    `submitter_biospecimen_id`: String = "BS_2",
    `sex`: String = "Female",
    `vital_status`: String = "Alive",
    `ethnicity`: String = "European",
    `is_a_proband`: Option[Boolean] = Some(false),
    `is_affected`: Option[Boolean] = Some(false),
    `participant_fhir_id`: String = "P2",
    `fhir_sample_id`: String = "FHIR_SAMPLE2",
    `sample_type`: String = "DNA (NCIT:C449)",
    `sample_id`: String = "SAMPLE2",
    `mother_id`: Option[String] = None,
    `father_id`: Option[String] = None,
    `family_id`: String = "FAMO1",
    `study_code`: String = "study_code1"
)
